package defpackage;

import com.google.android.gms.common.api.Status;

public class abo<R extends xk> extends xi<R> {
    private final Status a;

    public Integer a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void a(xl<? super R> xlVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status b() {
        return this.a;
    }
}
